name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python 2.7
        uses: actions/setup-python@v3
        with:
          python-version: 2.7
      
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir typing==3.7.4.1
          pip install --ignore-installed -r requirements.txt -e .[tests,docs]
      
      - name: Run tests with pytest and generate report
        run: coverage run -m pytest
      
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
      
  build:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: scoap3/hepcrawl:latest,scoap3/hepcrawl:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy QA
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.event_name == 'push'}}
        with:
          token: ${{ secrets.INSPIRE_BOT_TOKEN }}
          repository: cern-sis/kubernetes
          event-type: deploy
          client-payload: '{"project": "scoap3", "application": "scoap3", "namespace": "scoap3-qa","image":"scoap3/hepcrawl","new_tag":"${{ github.sha }}"}'

      - name: Build and push PROD
        id: docker_build_prod
        if: ${{ github.event_name == 'release'}}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: scoap3/hepcrawl:${{ github.ref_name }}

      - name: Deploy PROD
        uses: peter-evans/repository-dispatch@v1
        if: ${{ github.event_name == 'release'}}
        with:
          token: ${{ secrets.INSPIRE_BOT_TOKEN }}
          repository: cern-sis/kubernetes
          event-type: deploy
          client-payload: '{"project": "scoap3", "application": "scoap3", "namespace": "scoap3-prod","image":"scoap3/hepcrawl","new_tag":"${{ github.ref_name }}"}'
